---
title: "BCAA_data"
author: "Martin Monkman"
date: "April 3, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code to summarize the BC Assessment data



```{r}
library(dplyr)
library(readr)
library(stringr)
library(tidyr)

library(ggplot2)


options(scipen=999)

```


read source file(s) 

```{r  message = FALSE}


#BCAA2017data_Kootenay <- read_csv("C:/@data/GitHub/housing-data-visualization-project/data/BCAA/BC Stats - Housing Policy Analysis Kootenay Columbia.csv")

# BCAA2017data_all <- read_csv("C:/@data/GitHub/housing-data-visualization-project/data/BCAA/BC Stats - Housing Policy Analysis Kootenay Columbia.csv", 
#                        col_types = cols(PID = "c"))
                                  

#setwd("C:/@data/GitHub/housing-data-visualization-project/data/BCAA")

BCAA2017data_all <- read_csv("BCAA/BC Stats - Housing Policy Analysis Kootenay Columbia.csv", 
                        col_types = cols(PID = "c"))



countKoot <- nrow(BCAA2017data_all)
countall <- countKoot


ls.str(BCAA2017data_all)


```


(merge all 7 regions into 1? might be best to wait until it is in the SQL database and run some wrangling on the server)

(too late!)

```{r}


BCAA2017data_newbit <- read_csv("BCAA/BC Stats - Housing Policy Analysis Fraser Valley.csv", 
                        col_types = cols(PID = "c"))

countFV <- nrow(BCAA2017data_newbit)
countall <- countall + countFV
                                  
BCAA2017data_all <- rbind(BCAA2017data_all, BCAA2017data_newbit)
rm(BCAA2017data_newbit)


###

BCAA2017data_newbit <- read_csv("BCAA/BC Stats - Housing Policy Analysis Greater Vancouver.csv", 
                        col_types = cols(PID = "c"))

countGV <- nrow(BCAA2017data_newbit)
countall <- countall + countGV

BCAA2017data_all <- rbind(BCAA2017data_all, BCAA2017data_newbit)
rm(BCAA2017data_newbit)

###

BCAA2017data_newbit <- read_csv("BCAA/BC Stats - Housing Policy Analysis Northern BC.csv", 
                        col_types = cols(PID = "c"))

countNBC <- nrow(BCAA2017data_newbit)
countall <- countall + countNBC

BCAA2017data_all <- rbind(BCAA2017data_all, BCAA2017data_newbit)
rm(BCAA2017data_newbit)


### 

BCAA2017data_newbit <- read_csv("BCAA/BC Stats - Housing Policy Analysis Thompson Okanagan.csv", 
                        col_types = cols(PID = "c"))
                                  
countTO <- nrow(BCAA2017data_newbit)
countall <- countall + countTO

BCAA2017data_all <- rbind(BCAA2017data_all, BCAA2017data_newbit)
rm(BCAA2017data_newbit)


### 

BCAA2017data_newbit <- read_csv("BCAA/BC Stats - Housing Policy Analysis Vancouver Island.csv", 
                        col_types = cols(PID = "c"))
                                  
countVI <- nrow(BCAA2017data_newbit)
countall <- countall + countVI

BCAA2017data_all <- rbind(BCAA2017data_all, BCAA2017data_newbit)
rm(BCAA2017data_newbit)


write_csv(BCAA2017data_all, "BCAA/BCAA2017data_all.csv")

```



---



## GEOGRAPHY (save for the db server)


read geography file

```{r  message = FALSE}

cadastre_da_2011 <- read_csv("C:/@data/GitHub/housing-data-visualization-project/data/geography/cadastre_da_2011.csv")

ls.str(cadastre_da_2011)

cadastre_da_2011_DAUID <- cadastre_da_2011 %>%
  select(PID, DAUID)

```

The Join


```{r}

BCAA2017data_all_geog <- BCAA2017data_all %>% 
  left_join(cadastre_da_2011_DAUID, by = "PID")

ls.str(BCAA2017data_all_geog)


```



---


## ANALYSIS


read the file

```{r}

BCAA2017data_all <- read_csv("BCAA/BCAA2017data_all.csv")

ls.str(BCAA2017data_all)

### filter by residential

BCAA2017_Residential <- BCAA2017data_all %>%
  filter(PROPERTY_TYPE == "Residential") 

write_csv(BCAA2017_Residential, "BCAA/BCAA2017_Residential.csv")


```



 and summarize

```{r}

BCAA2017_Residential <- read_csv("BCAA2017_Residential.csv")

BCAA2017_Residential %>%
  group_by(PRIMARY_ACTUAL_USE) %>%
  summarise(number = n(), avg_FMV = mean(ACTUAL_TOTAL))

BCAA2017_Res_SFD <- BCAA2017_Residential %>%
  filter(PRIMARY_ACTUAL_USE == "000 - Single Family Dwelling")

summary(BCAA2017_Res_SFD$ACTUAL_TOTAL)

ggplot(BCAA2017_Res_SFD, aes(x=ACTUAL_TOTAL)) +
  geom_histogram(binwidth = 250000)

ggplot(BCAA2017_Res_SFD, aes(x=REGIONAL_DISTRICT, y=ACTUAL_TOTAL)) +
  geom_boxplot()

BCAA2017_Res_SFD %>%
  mutate(bin = ntile(ACTUAL_TOTAL, 10)) %>%
  group_by(bin) %>%
  summarise(number = n(), min = min(ACTUAL_TOTAL), max = max(ACTUAL_TOTAL))


BCAA2017_Res_SFD %>%
  mutate(bin = ntile(ACTUAL_TOTAL, 10)) %>%
  group_by(bin) %>%
  summarise(number = n(), min = min(ACTUAL_TOTAL), max = max(ACTUAL_TOTAL))


BCAA2017_Res_SFD$bin <- cut(BCAA2017_Res_SFD$ACTUAL_TOTAL, 
                            breaks = seq(0, 100000000, by = 250000))

table(BCAA2017_Res_SFD$bin)

```





